# Welcome to Jekyll!
#

# Site settings
title: <font color = '#ff0090'>Hello-FOSS </font>
description: |
  Official Website of the <font color = '#ff0090'>Hello-FOSS </font>festival  
  organised by [WnCC, IITB](https://www.wncc-iitb.org/) and [DevCom, IITB](https://devcom-iitb.org/)
owner: WnCC, IIT Bombay # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hellofoss.wncc-iitb.org" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/wncc
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://www.facebook.com/wncc.iitb
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://www.instagram.com/wncc.iitb/
  youtube-square: https://www.youtube.com/channel/UCs3x_XxwScIAzDUfN1lbbGw
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
